import { AI_CONFIG } from './config';

export interface FormattedAIResponse {
  success: boolean;
  content: string;
  brand: string;
  timestamp: string;
  error?: string;
}

export function formatAIResponse(text: string): FormattedAIResponse {
  if (!text || text.trim().length === 0) {
    return {
      success: false,
      content: `${AI_CONFIG.brandEmoji} Servorix AI was unable to generate a response. Please try again.`,
      brand: `${AI_CONFIG.brandEmoji} ${AI_CONFIG.brandName}`,
      timestamp: new Date().toISOString(),
      error: 'Empty response text generated by provider',
    };
  }

  // Ensure consistent branding
  const sanitizedText = text
    .replace(/Google Gemini/gi, AI_CONFIG.brandName)
    .replace(/Gemini/gi, AI_CONFIG.brandName)
    .replace(/Google AI/gi, AI_CONFIG.brandName);

  return {
    success: true,
    content: sanitizedText,
    brand: `${AI_CONFIG.brandEmoji} ${AI_CONFIG.brandName}`,
    timestamp: new Date().toISOString(),
  };
}

export function formatAIErrorResponse(userFriendlyError: string, internalErrorType?: string): FormattedAIResponse {
  return {
    success: false,
    content: userFriendlyError,
    brand: `${AI_CONFIG.brandEmoji} ${AI_CONFIG.brandName}`,
    timestamp: new Date().toISOString(),
    error: internalErrorType || 'AI Processing Error',
  };
}
